# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.33.40"
  config.vm.provision :shell, path: "provision/bootstrap.sh"

  config.vm.synced_folder "../project/", "/home/vagrant/projects/bot",
    create: true,
    mount_options: ["dmode=770,fmode=664"]

  config.vm.synced_folder "../project/bin/", "/home/vagrant/projects/bot/bin",
    create: true,
    mount_options: ["dmode=770,fmode=775"]

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
